name: CI Pipeline

on: [push]

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug Structure
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Mencari lokasi file secara dinamis agar tidak error
          FILE_PATH=$(find . -name "modelling_tuning.py" | head -n 1)
          python "$FILE_PATH"

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: artifacts/

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          LATEST_RUN_ID=$(ls artifacts/predictions_*.csv | head -n 1 | cut -d'_' -f2 | cut -d'.' -f1)
          IMAGE_TAG="$DOCKER_USERNAME/house-price-model:$LATEST_RUN_ID"
          docker build -t "$IMAGE_TAG" .
          docker push "$IMAGE_TAG"
