name: CI Pipeline

on: [push]

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install mlflow scikit-learn pandas dagshub kaggle

      - name: Run training
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow run MLProject --env-manager=local

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          RUN_ID=$(cat MLProject/last_run_id.txt)
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/house-price-model:$RUN_ID"
          
          docker build -t "$IMAGE_NAME" .

      - name: Push Docker Image
        run: |
          RUN_ID=$(cat MLProject/last_run_id.txt)
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/house-price-model:$RUN_ID"